### ISSUE TITLE
编译最新KernelSu内核出错

### ISSUE THREAD

**Issue by L1ngYu** [chilan666/withksuAndroid-Kernel-Builder#2]
[logs_24643250207.zip](https://github.com/user-attachments/files/15737619/logs_24643250207.zip)

**Comment by chilan666** [comment]
OK我处理下

**Comment by chilan666** [comment]
这可能是ksu更新之后导致的，我最近不怎么接触ksu，我得看看怎么回事

**Comment by chilan666** [comment]
ksu对非GKI内核已经停止支持，非GKI内核可以使用ksu的最大版本是0.9.5

**Comment by chilan666** [comment]
ksu对非GKI内核已经停止支持，非GKI内核可以使用ksu的最大版本是0.9.5
